### ISSUE TITLE
Add option to download the pdf

### ISSUE THREAD

**Issue by neomib-paylists** [TaTo30/vue-pdf#110]
Hello,
Is there an option to download the pdf? It will be very helpful. Thank you.

**Comment by senguyen1011** [comment]
You can implement this yourself! If you add a `download` attribute on an `<a>`, it'll create a downloadable link.
```typescript
<a
  :href="`/public/files/${props.name}.pdf`"
  download
>
  Download Here!
</a>
```

**Comment by TaTo30** [comment]
There are several ways to download files with vanilla js or using other libraries, if you already have the source file (how is supposed to be since this library requires it) you could use @senguyen1011 solution.

Anyways if you have an specific situation let us know and feel free to reopen the issue. 😊
