### ISSUE TITLE
Can't find and highlight umlauts

### ISSUE THREAD

**Issue by nataliia-obraztsova** [TaTo30/vue-pdf#141]
## Problem description

Text containing umlauts is not highlighted.

**Example 1: phrase until umlauts is matched**
const highlightText = ref('Arbeitszeit richten sich nach der betrieblichen Einteilung. 5. Urlaub Der Arbeitnehmer hat Anspruch auf einen gesetzlichen Mindesturlaub von derzeit 28 Arbeitstagen im Kalenderjahr-ausgehend von einer')

![image](https://github.com/user-attachments/assets/04f7ba8f-eb2e-48bc-addc-cd2ea355f581)

**Example 2: phrase including umlauts is no longer matched**
const highlightText = ref('Arbeitszeit richten sich nach der betrieblichen Einteilung. 5. Urlaub Der Arbeitnehmer hat Anspruch auf einen gesetzlichen Mindesturlaub von derzeit 28 Arbeitstagen im Kalenderjahr-ausgehend von einer Fünf-Tage-Woche. ')

![image](https://github.com/user-attachments/assets/9072a011-03e7-427b-8398-059e94d1aebe)

## Expected behavior
String 'Arbeitszeit richten sich nach der betrieblichen Einteilung. 5. Urlaub Der Arbeitnehmer hat Anspruch auf einen gesetzlichen Mindesturlaub von derzeit 28 Arbeitstagen im Kalenderjahr-ausgehend von einer Fünf-Tage-Woche.' is highlighted.

**Additional context**
 - vue-pdf: 1.11.0
 - vue: 3
 - pdfjs-dist: 4.6.82

## PDF document to test
[Extraction_Demo_Vertrag_Darth_Vder Galt.pdf](https://github.com/user-attachments/files/16845238/Extraction_Demo_Vertrag_Darth_Vder.Galt.pdf)

## Code to reproduce
```vue
<template>
    <VuePDF class="rounded-md border-2 border-gray-400 border-solid p-1 m-4 flex justify-center"
            :page="props.pageNumber || 1"
            :pdf="pdf" text-layer :highlight-text="highlightText3" :highlight-options="highlightOptions"/>

</template>

<script setup lang="ts">
import { VuePDF, usePDF } from '@tato30/vue-pdf'
import { ref } from 'vue'
import '@tato30/vue-pdf/style.css';
import * as PDFJS from 'pdfjs-dist'
PDFJS.GlobalWorkerOptions.workerSrc = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.6.82/build/pdf.worker.min.mjs'

const props = defineProps({
  pdfURL: {type: String, required: true},
  highlightText: {type: String, required: true},
  pageNumber: {type: Number, required: true}
})
const { pdf } = usePDF(props.pdfURL)

const highlightText3 = ref("Arbeitszeit richten sich nach der betrieblichen Einteilung. 5. Urlaub Der Arbeitnehmer hat Anspruch auf einen gesetzlichen Mindesturlaub von derzeit 28 Arbeitstagen im Kalenderjahr-ausgehend von einer Fünf-Tage-Woche.")
const highlightOptions = ref({
  completeWords: false,
  ignoreCase: true,
})
</script>

<style scoped>
</style>
```

**Comment by TaTo30** [comment]
This issue is not related to umlauts, if You try this text: `Die regelmäßige wöchentliche Arbeitszeit betr ägt 38 Stunden` the text with umlauts will be highlighted

![imagen](https://github.com/user-attachments/assets/477dc2d1-4c95-4450-b60a-747c5880b125)

In this text `von einer Fünf-Tage-Woche` the `Fünf` word has a whitespace (for some reason) in the middle: `Fü nf`.

That behavior is the same on the Firefox viewer

![imagen](https://github.com/user-attachments/assets/32315c15-0cdf-4b5a-8646-f48a6ec48d2a)
![imagen](https://github.com/user-attachments/assets/61c32e6f-6849-4e47-a5f9-46d190d04799)

This is issue is more related on how the PDF was generated instead of the viewer.
